name: Dependency audit

on:
  schedule:
    - cron: '23 14 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    uses: vyamoh/.github/.github/workflows/dependency-audit.yml@v1
    with:
      working-directories: '["."]'
